# permissions for end users to view infrastructures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infrastructure-viewer-role
rules:
- apiGroups:
  - eggo.isula.org
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eggo.isula.org
  resources:
  - infrastructures/status
  verbs:
  - get
