# permissions for end users to edit machinebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinebinding-editor-role
rules:
- apiGroups:
  - eggo.isula.org
  resources:
  - machinebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eggo.isula.org
  resources:
  - machinebindings/status
  verbs:
  - get
